version: '3'

services:
  backend:
    image: jpablovazquez/proyecto-back:latest
    expose:
      - 5000
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=app.py
  frontend:
    image: jpablovazquez/proyecto-front:latest
    expose:
      - 3000
    ports:
      - 3000:80
    depends_on:
      - backend